/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.HDPhatDAO;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;
import java.awt.Image;
import javax.swing.JFrame;
import model.ChiTietHDPhat;
import model.HDPhat;

/**
 *
 * @author ASUS
 */
public final class ChiTietCTHDPhat extends javax.swing.JFrame {

    /**
     * Creates new form ThemHoaDon
     */
    private ChiTietHDPhat cthdp;
    private HDPhat hdp;
    
    public ChiTietCTHDPhat() {
        initComponents();
    }
    
    public ChiTietCTHDPhat(ChiTietHDPhat cthdp) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        this.cthdp = cthdp;
        this.hdp = HDPhatDAO.getInstance().selectById(Integer.toString(cthdp.getMaHDP()));
        jLabel_MaHDP.setText(Integer.toString(cthdp.getMaHDP()));
        jLabel_TGTao.setText(hdp.getTGTao().format(dtf));
        jLabel_MaHD.setText(Integer.toString(hdp.getMaHD()));
        jLabel_MaXe.setText(Integer.toString(cthdp.getMaXe()));
        jLabel_SoTien.setText(cthdp.getSoTien() + "đ");
        jLabel_LoaiPhat.setText(cthdp.getLoaiPhat());
        jLabel_ChuThich.setText(cthdp.getChuThich());
        jLabel_Hinh.setIcon(ResizeImage(null, cthdp.getHinhAnh()));
    }
    
    public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage = null;
        
        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jLabel_Hinh.getWidth(), jLabel_Hinh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_Hinh = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel_MaHDP = new javax.swing.JLabel();
        jLabel_ChuThich = new javax.swing.JLabel();
        jLabel_MaHD = new javax.swing.JLabel();
        jLabel_TGTao = new javax.swing.JLabel();
        jLabel_MaXe = new javax.swing.JLabel();
        jLabel_LoaiPhat = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel_SoTien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(152, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT HÓA ĐƠN PHẠT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 30, 570, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 78, 570, 9));

        jLabel_Hinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel_Hinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 320, 220));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Mã hóa đơn phạt:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Thời gian tạo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Mã hóa đơn:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 120, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Mã xe:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 110, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Loại phạt:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 110, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("Hình ảnh:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 120, 30));

        jLabel_MaHDP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_MaHDP.setText("jLabel9");
        jPanel1.add(jLabel_MaHDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 120, 30));

        jLabel_ChuThich.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_ChuThich.setText("jLabel9");
        jLabel_ChuThich.setToolTipText("");
        jLabel_ChuThich.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel_ChuThich, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 340, 30));

        jLabel_MaHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_MaHD.setText("jLabel9");
        jPanel1.add(jLabel_MaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 120, 30));

        jLabel_TGTao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_TGTao.setText("jLabel9");
        jPanel1.add(jLabel_TGTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 130, 30));

        jLabel_MaXe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_MaXe.setText("jLabel9");
        jPanel1.add(jLabel_MaXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 130, 30));

        jLabel_LoaiPhat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_LoaiPhat.setText("jLabel9");
        jPanel1.add(jLabel_LoaiPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 130, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Số tiền:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 120, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Chú thích:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, 30));

        jLabel_SoTien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_SoTien.setText("jLabel9");
        jLabel_SoTien.setToolTipText("");
        jLabel_SoTien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel_SoTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietCTHDPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietCTHDPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietCTHDPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietCTHDPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietCTHDPhat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ChuThich;
    private javax.swing.JLabel jLabel_Hinh;
    private javax.swing.JLabel jLabel_LoaiPhat;
    javax.swing.JLabel jLabel_MaHD;
    private javax.swing.JLabel jLabel_MaHDP;
    private javax.swing.JLabel jLabel_MaXe;
    private javax.swing.JLabel jLabel_SoTien;
    private javax.swing.JLabel jLabel_TGTao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
