/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ChiTietHDDAO;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.ChiTietHD;


/**
 *
 * @author ASUS
 */
public class ChiTietHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form ThemHoaDon
     */
    private HoaDon hd;
    
    public ChiTietHoaDon() {
        initComponents();
        
    }
    
    public ChiTietHoaDon(HoaDon hd) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        this.hd = hd;
        jLabel_MaHD.setText(Integer.toString(hd.getMaHD()));
        jLabel_TGTao.setText(hd.getTGTao().format(dtf));
        jLabel_TGNhan.setText(hd.getTGNhan().format(dtf));
        jLabel_TGTra.setText(hd.getTGTra().format(dtf));
        jLabel_MaKH.setText(Integer.toString(hd.getMaKH()));
        jLabel_MaNV.setText(Integer.toString(hd.getMaNV()));
        jLabel_TongTienThue.setText(hd.getTongTienThue() + "đ");
        jLabel_TongTienCoc.setText(hd.getTongTienCoc() + "đ");
        jLabel_TinhTrang.setText(hd.getTinhTrang());
        jLabel_TGCapNhat.setText(hd.getTGCapNhat().format(dtf));
        jLabel_ChuThich.setText(hd.getChuThich());
        jTable_ChiTietHD.setDefaultEditor(Object.class, null);
        loadDataToTable_CTHD();
        
    }
    
    public void loadDataToTable_CTHD() {
        try {
            ArrayList<ChiTietHD> cthd = ChiTietHDDAO.getInstance().selectByMaHD(Integer.toString(hd.getMaHD()));
            DefaultTableModel tblcthdModel = (DefaultTableModel) jTable_ChiTietHD.getModel();
            tblcthdModel.setRowCount(0);
            for (ChiTietHD i : cthd) {
                tblcthdModel.addRow(new Object[]{
                    i.getMaHD(), i.getMaXe(), i.getSoNgay(), i.getSoTien(), i.getMaHopDong()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ChiTietHD = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_ChuThich = new javax.swing.JLabel();
        jLabel_MaHD = new javax.swing.JLabel();
        jLabel_TongTienCoc = new javax.swing.JLabel();
        jLabel_MaKH = new javax.swing.JLabel();
        jLabel_TongTienThue = new javax.swing.JLabel();
        jLabel_TinhTrang = new javax.swing.JLabel();
        jLabel_TGNhan = new javax.swing.JLabel();
        jLabel_TGTao = new javax.swing.JLabel();
        jLabel_TGTra = new javax.swing.JLabel();
        jLabel_MaNV = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_TGCapNhat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(152, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT HÓA ĐƠN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 701, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Mã hóa đơn:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 123, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Thời gian tạo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 110, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Thời gian cập nhật:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 140, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Chú thích:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 123, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Thời gian nhận:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 123, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Thời gian trả:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 110, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Mã nhân viên:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 110, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Mã khách hàng:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 123, 30));

        jTable_ChiTietHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_ChiTietHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Mã xe", "Số giờ", "Số tiền", "Mã hợp đồng giấy"
            }
        ));
        jScrollPane1.setViewportView(jTable_ChiTietHD);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 701, 270));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Tổng tiền thuê:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 123, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Tình trạng:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 123, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 78, 701, 9));

        jLabel_ChuThich.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_ChuThich.setText("jLabel9");
        jPanel1.add(jLabel_ChuThich, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 490, 30));

        jLabel_MaHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_MaHD.setText("jLabel9");
        jPanel1.add(jLabel_MaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 150, 30));

        jLabel_TongTienCoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_TongTienCoc.setText("jLabel9");
        jPanel1.add(jLabel_TongTienCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 150, 30));

        jLabel_MaKH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_MaKH.setText("jLabel9");
        jLabel_MaKH.setToolTipText("");
        jLabel_MaKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 150, 30));

        jLabel_TongTienThue.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_TongTienThue.setText("jLabel9");
        jPanel1.add(jLabel_TongTienThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 150, 30));

        jLabel_TinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_TinhTrang.setText("jLabel9");
        jPanel1.add(jLabel_TinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 150, 30));

        jLabel_TGNhan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_TGNhan.setText("jLabel9");
        jPanel1.add(jLabel_TGNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 150, 30));

        jLabel_TGTao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_TGTao.setText("jLabel9");
        jPanel1.add(jLabel_TGTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 150, 30));

        jLabel_TGTra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_TGTra.setText("jLabel9");
        jPanel1.add(jLabel_TGTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 150, 30));

        jLabel_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_MaNV.setText("jLabel9");
        jPanel1.add(jLabel_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 150, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Tổng tiền cọc:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 110, 30));

        jLabel_TGCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_TGCapNhat.setText("jLabel9");
        jPanel1.add(jLabel_TGCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ChuThich;
    private javax.swing.JLabel jLabel_MaHD;
    private javax.swing.JLabel jLabel_MaKH;
    private javax.swing.JLabel jLabel_MaNV;
    private javax.swing.JLabel jLabel_TGCapNhat;
    javax.swing.JLabel jLabel_TGNhan;
    private javax.swing.JLabel jLabel_TGTao;
    private javax.swing.JLabel jLabel_TGTra;
    private javax.swing.JLabel jLabel_TinhTrang;
    private javax.swing.JLabel jLabel_TongTienCoc;
    private javax.swing.JLabel jLabel_TongTienThue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_ChiTietHD;
    // End of variables declaration//GEN-END:variables
}
