/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.DanhGia;
import dao.DanhGiaDAO;
import controller.DanhGiacontroller;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public final class DanhGiaForm extends javax.swing.JPanel {

    /**
     * Creates new form DanhGiaForm
     */
    private DefaultTableModel tblModel;
    private static ArrayList<DanhGia> ds;
    
    public DanhGiaForm() {
        initComponents();
        tblDanhGia.setDefaultEditor(Object.class, null);
        tblDanhGia.getTableHeader().setFont(tblDanhGia.getFont().deriveFont(16));
        initTable();
        ds = DanhGiaDAO.getInstance().selectAll();
        loadDataToTable(ds);
        tblDanhGia.getColumnModel().getColumn(2).setPreferredWidth(700);
    }

    // Phương thức khởi tạo bảng
    public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã đánh giá", "Số điểm", "Nội dung", "Mã hóa đơn"};
        tblModel.setColumnIdentifiers(headerTbl);
        tblDanhGia.setModel(tblModel);
    }
    
    // Phương thức tải dữ liệu vào bảng
    public void loadDataToTable(ArrayList<DanhGia> dg) {
        try {
            // Xóa các hàng hiện có
            tblModel.setRowCount(0);
            // Thêm từng phần tử trong danh sách DanhGia vào bảng dưới dạng một hàng mới
            for (DanhGia i : dg) {
                    tblModel.addRow(new Object[]{
                    i.getMaDG(), i.getSoDiem(), i.getNoiDung(), i.getMaHD()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Phương thức lấy DanhGia đã chọn từ bảng
    public DanhGia getDanhGiaSelect(){
        int i_row = tblDanhGia.getSelectedRow();
        DanhGia dg = DanhGiaDAO.getInstance().selectAll().get(i_row);
        return dg;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhGia = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        cbxLuachon = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 820));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDanhGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã đánh giá", "Số điểm", "Nội dung", "Mã hóa đơn"
            }
        ));
        jScrollPane1.setViewportView(tblDanhGia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 1010, 530));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxLuachon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxLuachon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã đánh giá", "Số điểm", "Nội dung", "Mã hóa đơn" }));
        jPanel3.add(cbxLuachon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 290, 40));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_search.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 40, 40));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 40, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 600, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(152, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐÁNH GIÁ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 990, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1010, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 1010, 10));

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 150, 47));

        btnXuatExcel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_xls.png"))); // NOI18N
        btnXuatExcel.setText(" Xuất Excel");
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });
        jPanel1.add(btnXuatExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 150, 47));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // Lấy lựa chọn từ combo box và văn bản tìm kiếm
        String luachon = (String) cbxLuachon.getSelectedItem();
        String text = txtSearch.getText();
        
        // Thực hiện tìm kiếm dựa trên lựa chọn
        ArrayList<DanhGia> result = new ArrayList<>();
        switch (luachon) {
            case "Tất cả" -> result = DanhGiacontroller.getInstance().tkTatCa(text);
            case "Mã đánh giá" -> result = DanhGiacontroller.getInstance().tkMaDG(text);
            case "Số điểm" -> result = DanhGiacontroller.getInstance().tkSoDiem(text);
            case "Nội dung" -> result = DanhGiacontroller.getInstance().tkNoiDung(text);
            case "Mã hóa đơn" -> result = DanhGiacontroller.getInstance().tkMaHD(text);
        }
        
        // Tải kết quả tìm kiếm vào bảng
        loadDataToTable(result);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // Lấy lựa chọn từ combo box và văn bản tìm kiếm
        String luachon = (String) cbxLuachon.getSelectedItem();
        String text = txtSearch.getText();
        ArrayList<DanhGia> result = new ArrayList<>();
        
        // Thực hiện tìm kiếm dựa trên lựa chọn
        switch (luachon) {
            case "Tất cả" -> result = DanhGiacontroller.getInstance().tkTatCa(text);
            case "Mã đánh giá" -> result = DanhGiacontroller.getInstance().tkMaDG(text);
            case "Số điểm" -> result = DanhGiacontroller.getInstance().tkSoDiem(text);
            case "Nội dung" -> result = DanhGiacontroller.getInstance().tkNoiDung(text);
            case "Mã hóa đơn" -> result = DanhGiacontroller.getInstance().tkMaHD(text);
        }
        
        // Tải kết quả tìm kiếm vào bảng
        loadDataToTable(result);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // Tạo form ThemDanhGia mới
        ThemDanhGia a = new ThemDanhGia();
        a.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // Làm mói lựa chọn, tìm kiếm, bảng
        txtSearch.setText("");
        cbxLuachon.setSelectedIndex(0);
        loadDataToTable(DanhGiaDAO.getInstance().selectAll());
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser jFileChooser = new JFileChooser();
            // Hiển thị cửa sổ lưu file
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                // Thêm phần mở rộng .xlsx vào file
                saveFile = new File(saveFile.toString() + ".xlsx");
                
                // Tạo workbook mới
                Workbook wb = new XSSFWorkbook();
                
                // Tạo sheet mới
                Sheet sheet = wb.createSheet("DanhGia");

                Row rowCol = sheet.createRow(0);
                for (int i = 0; i < tblDanhGia.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(tblDanhGia.getColumnName(i));
                }
 
                for (int j = 0; j < tblDanhGia.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < tblDanhGia.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);
                        if (tblDanhGia.getValueAt(j, k) != null) {
                            cell.setCellValue(tblDanhGia.getValueAt(j, k).toString());
                        }

                    }
                }
                
                // Ghi workbook vào file
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                
                // Đóng workbook, mở file
                wb.close();
                out.close();
                openFile(saveFile.toString());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXuatExcelActionPerformed
                                         

    // Phương thức mở một file
    private void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException e) {
            System.out.println(e);
        }
    }                                            


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JComboBox<String> cbxLuachon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblDanhGia;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
