/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
public class HoaDonPhatForm extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonPhatForm
     */
    public HoaDonPhatForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_HDPhat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_ThemHDP = new javax.swing.JButton();
        jButton_CTHDP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbxLuachon = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jButton_TimKiemHDP = new javax.swing.JButton();
        jButton_ExcelHDP = new javax.swing.JButton();
        jButton_SuaHDP = new javax.swing.JButton();
        jButton_XoaHDP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_HDPhat = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel_HDPhat.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_HDPhat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(152, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HÓA ĐƠN PHẠT");
        jPanel_HDPhat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1010, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_HDPhat.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1010, 14));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_HDPhat.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 1010, 17));

        jButton_ThemHDP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ThemHDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_add.png"))); // NOI18N
        jButton_ThemHDP.setText(" Thêm");
        jButton_ThemHDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ThemHDPMouseClicked(evt);
            }
        });
        jButton_ThemHDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemHDPActionPerformed(evt);
            }
        });
        jPanel_HDPhat.add(jButton_ThemHDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 120, 41));

        jButton_CTHDP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_CTHDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_detail.png"))); // NOI18N
        jButton_CTHDP.setText(" Xem chi tiết");
        jButton_CTHDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CTHDPActionPerformed(evt);
            }
        });
        jPanel_HDPhat.add(jButton_CTHDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 174, 41));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxLuachon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxLuachon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa đơn phạt", "Ngày tạo", "Số tiền", "Chú thích", "Tình trạng", "Mã hợp đồng" }));
        cbxLuachon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLuachonActionPerformed(evt);
            }
        });
        jPanel3.add(cbxLuachon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 40));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSearchInputMethodTextChanged(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSearchPropertyChange(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 300, 40));

        jButton_TimKiemHDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_search.png"))); // NOI18N
        jButton_TimKiemHDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemHDPActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_TimKiemHDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 40, 40));

        jPanel_HDPhat.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 570, 90));

        jButton_ExcelHDP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ExcelHDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_xls.png"))); // NOI18N
        jButton_ExcelHDP.setText(" Xuất Excel");
        jButton_ExcelHDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcelHDPActionPerformed(evt);
            }
        });
        jPanel_HDPhat.add(jButton_ExcelHDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 173, 41));

        jButton_SuaHDP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_SuaHDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_update.png"))); // NOI18N
        jButton_SuaHDP.setText(" Sửa");
        jButton_SuaHDP.setToolTipText("");
        jButton_SuaHDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaHDPActionPerformed(evt);
            }
        });
        jPanel_HDPhat.add(jButton_SuaHDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 120, 41));

        jButton_XoaHDP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_XoaHDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_delete.png"))); // NOI18N
        jButton_XoaHDP.setText(" Xóa");
        jButton_XoaHDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaHDPActionPerformed(evt);
            }
        });
        jPanel_HDPhat.add(jButton_XoaHDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 120, 41));

        jTable_HDPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn phạt", "Ngày tạo", "Số tiền", "Chú thích", "Tình trạng", "Mã hợp đồng"
            }
        ));
        jScrollPane1.setViewportView(jTable_HDPhat);

        jPanel_HDPhat.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 1010, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_HDPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_HDPhat, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemHDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ThemHDPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ThemHDPMouseClicked

    private void jButton_ThemHDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemHDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ThemHDPActionPerformed

    private void jButton_CTHDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CTHDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CTHDPActionPerformed

    private void cbxLuachonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLuachonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLuachonActionPerformed

    private void txtSearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSearchInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchInputMethodTextChanged

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSearchPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchPropertyChange

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton_TimKiemHDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemHDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TimKiemHDPActionPerformed

    private void jButton_ExcelHDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcelHDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ExcelHDPActionPerformed

    private void jButton_SuaHDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaHDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SuaHDPActionPerformed

    private void jButton_XoaHDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaHDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_XoaHDPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxLuachon;
    private javax.swing.JButton jButton_CTHDP;
    private javax.swing.JButton jButton_ExcelHDP;
    private javax.swing.JButton jButton_SuaHDP;
    private javax.swing.JButton jButton_ThemHDP;
    private javax.swing.JButton jButton_TimKiemHDP;
    private javax.swing.JButton jButton_XoaHDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_HDPhat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_HDPhat;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
