/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ChiTietHDDAO;
import dao.HoaDonDAO;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChiTietHD;
import model.HoaDon;

/**
 *
 * @author ASUS
 */
public class SuaHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form ThemHoaDon
     */
    private HoaDon hd;
    
    public SuaHoaDon() {
        initComponents();
    }
    
    public SuaHoaDon(HoaDon hd) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        this.hd = hd;
        jTextField_MaHD.setText(Integer.toString(hd.getMaHD()));
        jTextField_TGTao.setText(hd.getTGTao().format(dtf));
        jTextField_TGNhan.setText(hd.getTGNhan().format(dtf));
        jTextField_TGTra.setText(hd.getTGTra().format(dtf));
        jTextField_MaKH.setText(Integer.toString(hd.getMaKH()));
        jTextField_MaNV.setText(Integer.toString(hd.getMaNV()));
        jTextField_TongTienThue.setText(hd.getTongTienThue() + "đ");
        jTextField_TongTienCoc.setText(hd.getTongTienCoc() + "đ");
        if(hd.getTinhTrang().equals("Đã đặt xe")){
            jComboBox_TinhTrang.setSelectedIndex(0);
        } else if(hd.getTinhTrang().equals("Đã nhận xe")){
            jComboBox_TinhTrang.setSelectedIndex(1);
        } else {
            jComboBox_TinhTrang.setSelectedIndex(2);
        }
        jTextArea_ChuThich.setText(hd.getChuThich());
        jTable_ChiTietHD.setDefaultEditor(Object.class, null);
        loadDataToTable_CTHD();
    }
    
    public void loadDataToTable_CTHD() {
        try {
            ArrayList<ChiTietHD> cthd = ChiTietHDDAO.getInstance().selectByMaHD(Integer.toString(hd.getMaHD()));
            DefaultTableModel tblcthdModel = (DefaultTableModel) jTable_ChiTietHD.getModel();
            tblcthdModel.setRowCount(0);
            for (ChiTietHD i : cthd) {
                tblcthdModel.addRow(new Object[]{
                    i.getMaHD(), i.getMaXe(), i.getSoNgay(), i.getSoTien(), i.getMaHopDong()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField_TGTra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_MaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ChiTietHD = new javax.swing.JTable();
        jButton_Thoat = new javax.swing.JButton();
        jButton_Luu = new javax.swing.JButton();
        jTextField_TongTienThue = new javax.swing.JTextField();
        jTextField_MaHD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_TGTao = new javax.swing.JTextField();
        jTextField_TGNhan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_TongTienCoc = new javax.swing.JTextField();
        jTextField_MaKH = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_ChuThich = new javax.swing.JTextArea();
        jComboBox_TinhTrang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(152, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SỬA HÓA ĐƠN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 701, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 701, 9));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Mã hóa đơn:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 120, 30));

        jTextField_TGTra.setEditable(false);
        jTextField_TGTra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField_TGTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TGTraActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_TGTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 190, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Ngày tạo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Tổng tiền thuê:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 120, 30));

        jTextField_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 190, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Thời gian trả:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 120, 27));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Mã nhân viên:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Chú thích:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 120, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Mã khách hàng:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 120, 30));

        jTable_ChiTietHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_ChiTietHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã CTHD", "Mã xe", "Số giờ", "Số tiền"
            }
        ));
        jScrollPane1.setViewportView(jTable_ChiTietHD);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 412, 701, 210));

        jButton_Thoat.setBackground(new java.awt.Color(153, 0, 0));
        jButton_Thoat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Thoat.setBorderPainted(false);
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 137, 30));

        jButton_Luu.setBackground(new java.awt.Color(27, 121, 30));
        jButton_Luu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_Luu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Luu.setText("Lưu");
        jButton_Luu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Luu.setBorderPainted(false);
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 142, 30));

        jTextField_TongTienThue.setEditable(false);
        jTextField_TongTienThue.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField_TongTienThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TongTienThueActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_TongTienThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 190, 30));

        jTextField_MaHD.setEditable(false);
        jTextField_MaHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField_MaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MaHDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_MaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 190, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Thời gian nhận:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 120, 27));

        jTextField_TGTao.setEditable(false);
        jTextField_TGTao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField_TGTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TGTaoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_TGTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 190, 30));

        jTextField_TGNhan.setEditable(false);
        jTextField_TGNhan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField_TGNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TGNhanActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_TGNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Tổng tiền cọc:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 120, 30));

        jTextField_TongTienCoc.setEditable(false);
        jTextField_TongTienCoc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField_TongTienCoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TongTienCocActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_TongTienCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 190, 30));

        jTextField_MaKH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 190, 33));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Tình trạng:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 120, 30));

        jTextArea_ChuThich.setColumns(20);
        jTextArea_ChuThich.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea_ChuThich.setRows(5);
        jScrollPane2.setViewportView(jTextArea_ChuThich);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 530, 50));

        jComboBox_TinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox_TinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã đặt xe", "Đã nhận xe", "Đã trả xe" }));
        jPanel1.add(jComboBox_TinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        // TODO add your handling code here:
        String makh = jTextField_MaKH.getText();
        String manv = jTextField_MaNV.getText();
        String tinhtrang = String.valueOf(jComboBox_TinhTrang.getSelectedItem());
        String chuthich = jTextArea_ChuThich.getText();
        if (makh.equals("") || manv.equals("") || tinhtrang.equals("") ) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !");
        } else {
            try {
                hd.setMaKH(Integer.parseInt(makh));
                hd.setMaNV(Integer.parseInt(manv));
                hd.setTinhTrang(tinhtrang);
                hd.setChuThich(chuthich);
                HoaDonDAO.getInstance().update(hd);
                this.dispose();
                JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công !");
                loadDataToTable_CTHD();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Sửa sản phẩm thất bại !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jTextField_TGTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TGTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TGTraActionPerformed

    private void jTextField_TongTienThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TongTienThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TongTienThueActionPerformed

    private void jTextField_MaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MaHDActionPerformed

    private void jTextField_TGTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TGTaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TGTaoActionPerformed

    private void jTextField_TGNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TGNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TGNhanActionPerformed

    private void jTextField_TongTienCocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TongTienCocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TongTienCocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JComboBox<String> jComboBox_TinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_ChiTietHD;
    private javax.swing.JTextArea jTextArea_ChuThich;
    private javax.swing.JTextField jTextField_MaHD;
    private javax.swing.JTextField jTextField_MaKH;
    private javax.swing.JTextField jTextField_MaNV;
    private javax.swing.JTextField jTextField_TGNhan;
    private javax.swing.JTextField jTextField_TGTao;
    private javax.swing.JTextField jTextField_TGTra;
    private javax.swing.JTextField jTextField_TongTienCoc;
    private javax.swing.JTextField jTextField_TongTienThue;
    // End of variables declaration//GEN-END:variables
}
