/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ChiTietHDDAO;
import dao.ChiTietHDPhatDAO;
import dao.HDPhatDAO;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.ChiTietHD;
import model.ChiTietHDPhat;
import model.HDPhat;

/**
 *
 * @author ASUS
 */
public class ThemCTHDPhat extends javax.swing.JFrame {

    /**
     * Creates new form ThemHoaDon
     */
    String ImgPath = null;
    
    public ThemCTHDPhat() {
        initComponents();
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_Thoat = new javax.swing.JButton();
        jButton_Luu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_ChuThich = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel_Hinh = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_MaHD = new javax.swing.JTextField();
        jComboBox_MaXe = new javax.swing.JComboBox<>();
        jButton_ChonHinh = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_LoaiPhat = new javax.swing.JComboBox<>();
        jTextField_SoTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(152, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT HÓA ĐƠN PHẠT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 570, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 78, 570, 9));

        jButton_Thoat.setBackground(new java.awt.Color(153, 0, 0));
        jButton_Thoat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_Thoat.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Thoat.setText("Thoát");
        jButton_Thoat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Thoat.setBorderPainted(false);
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 628, 137, 30));

        jButton_Luu.setBackground(new java.awt.Color(27, 121, 30));
        jButton_Luu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_Luu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Luu.setText("Lưu");
        jButton_Luu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Luu.setBorderPainted(false);
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 628, 142, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Loại phạt:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 123, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Mã xe:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 123, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Hình ảnh:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 123, 30));

        jTextArea_ChuThich.setColumns(20);
        jTextArea_ChuThich.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea_ChuThich.setRows(5);
        jScrollPane2.setViewportView(jTextArea_ChuThich);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 570, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Chú thích:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 123, 27));

        jLabel_Hinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_Hinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel_Hinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 310, 180));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Mã hóa đơn:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, 30));

        jTextField_MaHD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField_MaHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_MaHDKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_MaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 240, 30));

        jComboBox_MaXe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jComboBox_MaXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 240, 30));

        jButton_ChonHinh.setBackground(new java.awt.Color(204, 204, 204));
        jButton_ChonHinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_ChonHinh.setText("Chọn hình");
        jButton_ChonHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChonHinhActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_ChonHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 110, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Số tiền:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 123, 30));

        jComboBox_LoaiPhat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox_LoaiPhat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thiệt hại", "Quá hạn" }));
        jPanel1.add(jComboBox_LoaiPhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 240, 30));

        jTextField_SoTien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField_SoTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        // TODO add your handling code here:
        String MaHD = jTextField_MaHD.getText();
        String MaXe = (String) jComboBox_MaXe.getSelectedItem();
        String LoaiPhat = (String) jComboBox_LoaiPhat.getSelectedItem();
        String SoTien = jTextField_SoTien.getText();
        String ChuThich = jTextArea_ChuThich.getText();
        
        try {
            if( MaHD.isEmpty() || MaXe.isEmpty() || LoaiPhat.isEmpty() || ChuThich.isEmpty() || SoTien.isEmpty()){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }else{
                int MaHDP = HDPhatDAO.getInstance().selectMaHDPByMaHD(Integer.parseInt(MaHD));
                if(MaHDP == 0 ){
                    MaHDP = HDPhatDAO.getInstance().selectMaHDPMax() + 1;
                    System.out.println(MaHDP);
                    HDPhat hdp = new HDPhat(MaHDP, LocalDate.now(), 0, "Chua thanh toán", Integer.parseInt(MaHD));
                    HDPhatDAO.getInstance().insert(hdp);
                }
                ChiTietHDPhat cthdp = new ChiTietHDPhat(MaHDP, Integer.parseInt(MaXe), LoaiPhat, Integer.parseInt(SoTien), null, ChuThich);
                if(ImgPath != null)
                    ChiTietHDPhatDAO.getInstance().insert(cthdp, ImgPath);
                else
                    ChiTietHDPhatDAO.getInstance().insert(cthdp);
                this.dispose();
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã không hợp lệ!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ThemCTHDPhat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jTextField_MaHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MaHDKeyReleased
        // TODO add your handling code here:
        jComboBox_MaXe.removeAllItems();
        String MaHD = jTextField_MaHD.getText();
        ArrayList<ChiTietHD> cthd = ChiTietHDDAO.getInstance().selectByMaHD(MaHD);
        for(ChiTietHD i : cthd){
            jComboBox_MaXe.addItem(Integer.toString(i.getMaXe()));
        }
    }//GEN-LAST:event_jTextField_MaHDKeyReleased

    private void jButton_ChonHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChonHinhActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
       
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabel_Hinh.setIcon(ResizeImage(path, null));
            ImgPath = path;
        }
        else{
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_jButton_ChonHinhActionPerformed
    
    public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage = null;

        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }

        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(jLabel_Hinh.getWidth(), jLabel_Hinh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemCTHDPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemCTHDPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemCTHDPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemCTHDPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemCTHDPhat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ChonHinh;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JComboBox<String> jComboBox_LoaiPhat;
    private javax.swing.JComboBox<String> jComboBox_MaXe;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Hinh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_ChuThich;
    private javax.swing.JTextField jTextField_MaHD;
    private javax.swing.JTextField jTextField_SoTien;
    // End of variables declaration//GEN-END:variables
}
